### ISSUE TITLE
Update readme regarding Flutter version

### ISSUE THREAD

**Issue by agnesjang98** [sendgrid/dx-mobile#18]
Since the repo was recently updated to use the newest version of Flutter (v0.9.4), we need to reflect that update on the [readme.](https://github.com/sendgrid/dx-mobile/blob/master/README.md)

**Comment by robotenique** [comment]
I can help with that. Does any of the installation and running process changes with the new Flutter version, or just to update the version in the readme?

**Comment by Millsky** [comment]
I can take this one

**Comment by michaelscof** [comment]
I have taken this one!
