### ISSUE TITLE
Use graphql_flutter package for working with Github GraphQL API

### ISSUE THREAD

**Issue by MaskyS** [sendgrid/dx-mobile#22]
https://pub.dartlang.org/packages/graphql_flutter looks pretty solid and should make things easier. Would you consider using it?

**Comment by agnesjang98** [comment]
Hi @MaskyS, I made an issue #26 with acceptance criteria if you'd like to try tackling it! I'm going to go ahead and close this issue for now and we can continue the conversation on #26.
